# Generated by Django 2.0.9 on 2018-10-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nie_hub', '0004_auto_20181012_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='attachments',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('branch', models.CharField(max_length=3)),
                ('sem', models.IntegerField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nie_hub.User')),
            ],
        ),
        migrations.AddField(
            model_name='attachments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Posts'),
        ),
    ]
