# Generated by Django 2.0.9 on 2018-11-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='links',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='branch',
            field=models.CharField(choices=[('CE', 'CE'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ISE', 'ISE'), ('ME', 'ME'), ('IPE', 'IPE')], max_length=3),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='sem',
            field=models.IntegerField(),
        ),
    ]
