# Generated by Django 2.0.9 on 2018-11-01 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181101_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='sem',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
    ]
