# Generated by Django 2.0.9 on 2018-11-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181121_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachments',
            name='link',
        ),
        migrations.AddField(
            model_name='attachments',
            name='attachment_link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
