# Generated by Django 2.0.9 on 2018-11-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nie_hub', '0007_auto_20181103_2116'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_details',
            fields=[
                ('item_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=3)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_items',
            fields=[
                ('item_trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nie_hub.User')),
                ('item_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Item_details')),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='interested_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item_details',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Items'),
        ),
    ]
