# Generated by Django 2.0.9 on 2018-11-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nie_hub', '0007_auto_20181103_2116'),
        ('events', '0003_auto_20181107_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiting_items',
            fields=[
                ('item_trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_quantity', models.IntegerField()),
                ('date', models.DateTimeField(null=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nie_hub.User')),
                ('item_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Item_details')),
            ],
        ),
    ]
