# Generated by Django 2.0.9 on 2018-11-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_waiting_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiting_items',
            old_name='item_trans_id',
            new_name='item_waiting_id',
        ),
    ]
