# Generated by Django 2.0.9 on 2018-11-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nie_hub', '0007_auto_20181103_2116'),
        ('events', '0007_auto_20181120_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_items',
            fields=[
                ('item_trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('quantity_sold', models.IntegerField()),
                ('size', models.CharField(max_length=3, null=True)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Shirts', 'Shirts'), ('Trousers', 'Trousers'), ('Caps', 'Caps'), ('Others', 'Others')], max_length=30)),
                ('name', models.CharField(max_length=30, null=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id', to='nie_hub.User')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to='nie_hub.User')),
            ],
        ),
    ]
