# Generated by Django 2.0.9 on 2018-11-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_transaction_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_items',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='transaction_items',
            name='owner_id',
        ),
        migrations.DeleteModel(
            name='Transaction_items',
        ),
    ]
