# Generated by Django 2.0.9 on 2018-10-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nie_hub', '0002_auto_20181006_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sem',
            field=models.IntegerField(null=True),
        ),
    ]
