# Generated by Django 2.0.9 on 2018-11-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nie_hub', '0004_auto_20181012_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('CE', 'CE'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ISE', 'ISE'), ('ME', 'ME'), ('IPE', 'IPE')], max_length=3),
        ),
    ]
