# Generated by Django 2.0.9 on 2018-11-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nie_hub', '0007_auto_20181103_2116'),
        ('nie_hub', '0006_auto_20181104_1625'),
    ]

    operations = [
    ]
